/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GymBookingSystem;

/**
 *
 * @author ooikn
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        manageBookingMenu = new javax.swing.JMenu();
        addBookingMenuItem = new javax.swing.JMenuItem();
        editBookingMenuItem = new javax.swing.JMenuItem();
        searchBookingMenuItem = new javax.swing.JMenuItem();
        deleteBookingMenuItem = new javax.swing.JMenuItem();
        trainerInfoMenu = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GymBookingSystem/pexels-willpicturethis-1954524.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 600, 400);

        jMenu1.setText("Homepage");
        jMenuBar1.add(jMenu1);

        manageBookingMenu.setText("Manage Booking");

        addBookingMenuItem.setText("Add Booking");
        addBookingMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookingMenuItemActionPerformed(evt);
            }
        });
        manageBookingMenu.add(addBookingMenuItem);

        editBookingMenuItem.setText("Edit Booking");
        editBookingMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBookingMenuItemActionPerformed(evt);
            }
        });
        manageBookingMenu.add(editBookingMenuItem);

        searchBookingMenuItem.setText("Search Booking");
        manageBookingMenu.add(searchBookingMenuItem);

        deleteBookingMenuItem.setText("Delete Booking");
        manageBookingMenu.add(deleteBookingMenuItem);

        jMenuBar1.add(manageBookingMenu);

        trainerInfoMenu.setText("View Trainer Information");
        jMenuBar1.add(trainerInfoMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editBookingMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBookingMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBookingMenuItemActionPerformed

    private void addBookingMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookingMenuItemActionPerformed
        AddBooking addBookingForm = new AddBooking();
        addBookingForm.setVisible(true);

    }//GEN-LAST:event_addBookingMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addBookingMenuItem;
    private javax.swing.JMenuItem deleteBookingMenuItem;
    private javax.swing.JMenuItem editBookingMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu manageBookingMenu;
    private javax.swing.JMenuItem searchBookingMenuItem;
    private javax.swing.JMenu trainerInfoMenu;
    // End of variables declaration//GEN-END:variables
}
