/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GymBookingSystem;

import javax.swing.JOptionPane;

/**
 *
 * @author ooikn
 */
public class MainGUI extends javax.swing.JFrame {
    private String memberId; 
    
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }
    /**
     * Creates new form GUI
     */
    public MainGUI() {
        initComponents();
        setSize(600, 425);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        profileMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        manageBookingMenu = new javax.swing.JMenu();
        addBookingMenuItem = new javax.swing.JMenuItem();
        editBookingMenuItem = new javax.swing.JMenuItem();
        searchBookingMenuItem = new javax.swing.JMenuItem();
        deleteBookingMenuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GymFitness");
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GymBookingSystem/pexels-willpicturethis-1954524.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 380);

        jMenu1.setText("Account");

        profileMenuItem.setText("Profile");
        profileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(profileMenuItem);

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(logoutMenuItem);

        jMenuBar1.add(jMenu1);

        manageBookingMenu.setText("Manage Booking");

        addBookingMenuItem.setText("Add Booking");
        addBookingMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookingMenuItemActionPerformed(evt);
            }
        });
        manageBookingMenu.add(addBookingMenuItem);

        editBookingMenuItem.setText("Edit Booking");
        editBookingMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBookingMenuItemActionPerformed(evt);
            }
        });
        manageBookingMenu.add(editBookingMenuItem);

        searchBookingMenuItem.setText("Search Booking");
        searchBookingMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookingMenuItemActionPerformed(evt);
            }
        });
        manageBookingMenu.add(searchBookingMenuItem);

        deleteBookingMenuItem.setText("Delete Booking");
        deleteBookingMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookingMenuItemActionPerformed(evt);
            }
        });
        manageBookingMenu.add(deleteBookingMenuItem);

        jMenuBar1.add(manageBookingMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editBookingMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBookingMenuItemActionPerformed
        UpdateBooking updateBookingForm = new UpdateBooking(memberId);
        updateBookingForm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        updateBookingForm.setVisible(true);
    }//GEN-LAST:event_editBookingMenuItemActionPerformed

    private void addBookingMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookingMenuItemActionPerformed
        AddBooking addBookingForm = new AddBooking(memberId);
        addBookingForm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        addBookingForm.setVisible(true);

    }//GEN-LAST:event_addBookingMenuItemActionPerformed

    private void searchBookingMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBookingMenuItemActionPerformed
        SearchAndDisplayBooking searchAndDisplayBookingForm = new SearchAndDisplayBooking();
        searchAndDisplayBookingForm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        searchAndDisplayBookingForm.setVisible(true);
    }//GEN-LAST:event_searchBookingMenuItemActionPerformed

    private void deleteBookingMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookingMenuItemActionPerformed
        DeleteBooking deleteBookingForm = new DeleteBooking(memberId);
        deleteBookingForm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        deleteBookingForm.setVisible(true);
    }//GEN-LAST:event_deleteBookingMenuItemActionPerformed

    private void profileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileMenuItemActionPerformed
        if(memberId != null){
            MemberProfile memberProfile = new MemberProfile(memberId);
            memberProfile.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            memberProfile.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "No member ID found. Please login again.");
        }
        
    }//GEN-LAST:event_profileMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        MemberLogin backToLoginPage = new MemberLogin();
        backToLoginPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addBookingMenuItem;
    private javax.swing.JMenuItem deleteBookingMenuItem;
    private javax.swing.JMenuItem editBookingMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenu manageBookingMenu;
    private javax.swing.JMenuItem profileMenuItem;
    private javax.swing.JMenuItem searchBookingMenuItem;
    // End of variables declaration//GEN-END:variables
}
